from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set 


class ItemDict(TypedDict, total=False): 
    classification: ItemClassification 
    count: int 
    name: str 
    doom_type: int # Unique numerical id used to spawn the item. -1 is level item, -2 is level complete item. 
    hub: int # Relevant if that item targets a specific level, like keycard or map reveal pickup. 
    map: int 


item_table: Dict[int, ItemDict] = {
    390000: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Timon\'s Axe',
             'doom_type': 8010,
             'hub': -1,
             'map': -1},
    390001: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Hammer of Retribution',
             'doom_type': 123,
             'hub': -1,
             'map': -1},
    390002: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Quietus Blade',
             'doom_type': 12,
             'hub': -1,
             'map': -1},
    390003: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Quietus Cross',
             'doom_type': 13,
             'hub': -1,
             'map': -1},
    390004: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Quietus Hilt',
             'doom_type': 16,
             'hub': -1,
             'map': -1},
    390005: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Serpent Staff',
             'doom_type': 10,
             'hub': -1,
             'map': -1},
    390006: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Firestorm',
             'doom_type': 8009,
             'hub': -1,
             'map': -1},
    390007: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Wraithverge Arc',
             'doom_type': 18,
             'hub': -1,
             'map': -1},
    390008: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Wraithverge Cross',
             'doom_type': 19,
             'hub': -1,
             'map': -1},
    390009: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Wraithverge Shaft',
             'doom_type': 20,
             'hub': -1,
             'map': -1},
    390010: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Frost Shards',
             'doom_type': 53,
             'hub': -1,
             'map': -1},
    390011: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Arc of Death',
             'doom_type': 8040,
             'hub': -1,
             'map': -1},
    390012: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Bloodscourge Skull',
             'doom_type': 21,
             'hub': -1,
             'map': -1},
    390013: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Bloodscourge Stub',
             'doom_type': 22,
             'hub': -1,
             'map': -1},
    390014: {'classification': ItemClassification.progression,
             'count': 0,
             'name': 'Bloodscourge Stick',
             'doom_type': 23,
             'hub': -1,
             'map': -1},
    390015: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Emerald Key',
             'doom_type': 8034,
             'hub': 1,
             'map': -1},
    390016: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Silver Key',
             'doom_type': 8036,
             'hub': 1,
             'map': -1},
    390017: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Steel Key',
             'doom_type': 8030,
             'hub': 1,
             'map': -1},
    390018: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fire Key',
             'doom_type': 8033,
             'hub': 1,
             'map': -1},
    390019: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Horn Key',
             'doom_type': 8038,
             'hub': 2,
             'map': -1},
    390020: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cave Key',
             'doom_type': 8031,
             'hub': 2,
             'map': -1},
    390021: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Swamp Key',
             'doom_type': 8039,
             'hub': 2,
             'map': -1},
    390022: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle Key',
             'doom_type': 8200,
             'hub': 2,
             'map': -1},
    390023: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Rusted Key',
             'doom_type': 8037,
             'hub': 4,
             'map': -1},
    390024: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dungeon Key',
             'doom_type': 8035,
             'hub': 4,
             'map': -1},
    390025: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Axe Key',
             'doom_type': 8032,
             'hub': 4,
             'map': -1},
    390026: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Flame Mask',
             'doom_type': 9014,
             'hub': 1,
             'map': -1},
    390027: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heart of D\'Sparil',
             'doom_type': 9003,
             'hub': 1,
             'map': -1},
    390028: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruby Planet',
             'doom_type': 9004,
             'hub': 3,
             'map': -1},
    390029: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Emerald Planet 1',
             'doom_type': 9005,
             'hub': 3,
             'map': -1},
    390030: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Emerald Planet 2',
             'doom_type': 9009,
             'hub': 3,
             'map': -1},
    390031: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sapphire Planet 1',
             'doom_type': 9006,
             'hub': 3,
             'map': -1},
    390032: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sapphire Planet 2',
             'doom_type': 9010,
             'hub': 3,
             'map': -1},
    390033: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Daemon Codex',
             'doom_type': 9007,
             'hub': 4,
             'map': -1},
    390034: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Liber Oscura',
             'doom_type': 9008,
             'hub': 4,
             'map': -1},
    390035: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Clock Gear 1',
             'doom_type': 9018,
             'hub': 4,
             'map': -1},
    390036: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Clock Gear 2',
             'doom_type': 9019,
             'hub': 4,
             'map': -1},
    390037: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Clock Gear 3',
             'doom_type': 9020,
             'hub': 4,
             'map': -1},
    390038: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Clock Gear 4',
             'doom_type': 9021,
             'hub': 4,
             'map': -1},
    390039: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Yorick\'s Skull',
             'doom_type': 9002,
             'hub': 4,
             'map': -1},
    390040: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Glaive Seal',
             'doom_type': 9015,
             'hub': 5,
             'map': -1},
    390041: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Holy Relic',
             'doom_type': 9016,
             'hub': 5,
             'map': -1},
    390042: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sigil of the Magus',
             'doom_type': 9017,
             'hub': 5,
             'map': -1},
    390043: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals',
             'doom_type': -1,
             'hub': 1,
             'map': 1},
    390044: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Complete',
             'doom_type': -2,
             'hub': 1,
             'map': 1},
    390045: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood',
             'doom_type': -1,
             'hub': 2,
             'map': 1},
    390046: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Complete',
             'doom_type': -2,
             'hub': 2,
             'map': 1},
    390047: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary',
             'doom_type': -1,
             'hub': 3,
             'map': 1},
    390048: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Complete',
             'doom_type': -2,
             'hub': 3,
             'map': 1},
    390049: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle of Grief',
             'doom_type': -1,
             'hub': 4,
             'map': 1},
    390050: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle of Grief - Complete',
             'doom_type': -2,
             'hub': 4,
             'map': 1},
    390051: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Necropolis',
             'doom_type': -1,
             'hub': 5,
             'map': 1},
    390052: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Necropolis - Complete',
             'doom_type': -2,
             'hub': 5,
             'map': 1},
    390053: {'classification': ItemClassification.progression,
             'count': 2,
             'name': 'Seven Portals - Seven Portals - West Access (1/3)',
             'doom_type': -3, # MAP02 Script 20
             'hub': 1,
             'map': -1},
    390054: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Seven Portals - Ice Stairs',
             'doom_type': -3, # MAP02 Script 16
             'hub': 1,
             'map': -1},
    390055: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Seven Portals - Steel Stairs',
             'doom_type': -3, # MAP02 Script 17
             'hub': 1,
             'map': -1},
    390056: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Seven Portals - Fire Stairs',
             'doom_type': -3, # MAP02 Script 18
             'hub': 1,
             'map': -1},
    390057: {'classification': ItemClassification.progression,
             'count': 3,
             'name': 'Seven Portals - Seven Portals - Exit Access (1/3)',
             'doom_type': -3, # MAP02 Script 9
             'hub': 1,
             'map': -1},
    390058: {'classification': ItemClassification.progression,
             'count': 2,
             'name': 'Seven Portals - Bright Crucible Access (1/2)',
             'doom_type': -3, # MAP02 Script 1
             'hub': 1,
             'map': -1},
    390059: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Guardian of Ice - Steel Door',
             'doom_type': -3, # MAP03 Script 21
             'hub': 1,
             'map': -1},
    390060: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Seven Portals - Guardian of Ice - Fire Door',
             'doom_type': -3, # MAP03 Script 22
             'hub': 1,
             'map': -1},
    390061: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle of Grief - Forsaken Outpost - Desolate Garden Access 1',
             'doom_type': -3, # MAP21 Script 8 (and 10)
             'hub': 4,
             'map': -1},
    390062: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Darkmere Horn Switch',
             'doom_type': -3, # MAP13 Script 18, world0 increment
             'hub': 2,
             'map': -1},
    390063: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Darkmere Cave Switch',
             'doom_type': -3, # MAP13 Script 19, world0 increment
             'hub': 2,
             'map': -1},
    390064: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Caves of Circe Horn Switch',
             'doom_type': -3, # MAP13 Script 20, world0 increment
             'hub': 2,
             'map': -1},
    390065: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Caves of Circe Swamp Switch',
             'doom_type': -3, # MAP13 Script 21, world0 increment
             'hub': 2,
             'map': -1},
    390066: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Wastelands Swamp Switch',
             'doom_type': -3, # MAP13 Script 22, world0 increment
             'hub': 2,
             'map': -1},
    390067: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shadow Wood - Shadow Wood - Wastelands Cave Switch',
             'doom_type': -3, # MAP13 Script 23, world0 increment
             'hub': 2,
             'map': -1},
    390068: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle of Grief - Forsaken Outpost - Desolate Garden Access 2',
             'doom_type': -3, # MAP21 Script 9 (and 10)
             'hub': 4,
             'map': -1},
    390069: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Dragon Chapel Dragon Switch',
             'doom_type': -3, # MAP27 Script 31, MAP34 Script 1, MAP30 Script 6
             'hub': 3,
             'map': -1},
    390070: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Dragon Chapel Wolf Switch',
             'doom_type': -3, # MAP27 Script 32
             'hub': 3,
             'map': -1},
    390071: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Dragon Chapel Griffin Switch',
             'doom_type': -3, # MAP27 Script 33
             'hub': 3,
             'map': -1},
    390072: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Griffin Chapel Griffin Switch',
             'doom_type': -3, # MAP27 Script 37, MAP28 Script 2, MAP34 Script 7
             'hub': 3,
             'map': -1},
    390073: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Griffin Chapel Dragon Switch',
             'doom_type': -3, # MAP27 Script 38
             'hub': 3,
             'map': -1},
    390074: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Griffin Chapel Wolf Trigger',
             'doom_type': -3, # MAP27 Script 39
             'hub': 3,
             'map': -1},
    390075: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Wolf Chapel Wolf Switch',
             'doom_type': -3, # MAP27 Script 34, MAP28 Script 5, MAP30 Script 5
             'hub': 3,
             'map': -1},
    390076: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Wolf Chapel Dragon Switch',
             'doom_type': -3, # MAP27 Script 35
             'hub': 3,
             'map': -1},
    390077: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Wolf Chapel Griffin Trigger',
             'doom_type': -3, # MAP27 Script 36
             'hub': 3,
             'map': -1},
    390078: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Castle of Grief - Gibbet - Axe Key Access',
             'doom_type': -3, # MAP23 Script 24
             'hub': 4,
             'map': -1},
    390079: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Blue Mana',
             'doom_type': 122,
             'hub': -1,
             'map': -1},
    390080: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Green Mana',
             'doom_type': 124,
             'hub': -1,
             'map': -1},
    390081: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Combined Mana',
             'doom_type': 8004,
             'hub': -1,
             'map': -1},
    390082: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Amulet of Warding',
             'doom_type': 8008,
             'hub': -1,
             'map': -1},
    390083: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Falcon Shield',
             'doom_type': 8006,
             'hub': -1,
             'map': -1},
    390084: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Mesh Armor',
             'doom_type': 8005,
             'hub': -1,
             'map': -1},
    390085: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Platinum Helm',
             'doom_type': 8007,
             'hub': -1,
             'map': -1},
    390086: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Dragonskin Bracers',
             'doom_type': 8041,
             'hub': -1,
             'map': -1},
    390087: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Mystic Urn',
             'doom_type': 32,
             'hub': -1,
             'map': -1},
    390088: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Banishment Device',
             'doom_type': 10040,
             'hub': -1,
             'map': -1},
    390089: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Boots of Speed',
             'doom_type': 8002,
             'hub': -1,
             'map': -1},
    390090: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Chaos Device',
             'doom_type': 36,
             'hub': -1,
             'map': -1},
    390091: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Dark Servant',
             'doom_type': 86,
             'hub': -1,
             'map': -1},
    390092: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Icon of the Defender',
             'doom_type': 84,
             'hub': -1,
             'map': -1},
    390093: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Krater of Might',
             'doom_type': 8003,
             'hub': -1,
             'map': -1},
    390094: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Porkalator',
             'doom_type': 30,
             'hub': -1,
             'map': -1},
    390095: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Torch',
             'doom_type': 33,
             'hub': -1,
             'map': -1},
    390096: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Disc of Repulsion',
             'doom_type': 10110,
             'hub': -1,
             'map': -1},
    390097: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Flechette',
             'doom_type': 8000,
             'hub': -1,
             'map': -1},
    390098: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Quartz Flask',
             'doom_type': 82,
             'hub': -1,
             'map': -1},
}


item_name_groups: Dict[str, Set[str]] = {
    'Ammos': {'Blue Mana', 'Green Mana', 'Combined Mana', },
    'Armors': {'Amulet of Warding', 'Falcon Shield', 'Mesh Armor', 'Platinum Helm', },
    'Artifacts': {'Dragonskin Bracers', 'Mystic Urn', 'Banishment Device', 'Boots of Speed', 'Chaos Device', 'Dark Servant', 'Icon of the Defender', 'Krater of Might', 'Porkalator' 'Torch', 'Disc of Repulsion', 'Flechette', 'Quartz Flask', },
    'Keys': {'Emerald Key', 'Silver Key', 'Steel Key', 'Fire Key', 'Horn Key', 'Cave Key', 'Swamp Key', 'Castle Key', 'Rusted Key', 'Dungeon Key', 'Axe Key', 'Flame Mask', 'Heart of D\'Sparil', 'Ruby Planet', 'Emerald Planet 1', 'Emerald Planet 2', 'Sapphire Planet 1', 'Sapphire Planet 2', 'Daemon Codex', 'Liber Oscura', 'Clock Gear 1', 'Clock Gear 2', 'Clock Gear 3', 'Clock Gear 4', 'Yorick\'s Skull', 'Glaive Seal', 'Holy Relic', 'Sigil of the Magus', }, 
    'Levels': {'Seven Portals', 'Shadow Wood', 'Heresiarch\'s Seminary', 'Castle of Grief', 'Necropolis', },
    'Weapons': {'Timon\'s Axe', 'Hammer of Retribution', 'Quietus Blade', 'Quietus Cross', 'Quietus Hilt', 'Serpent Staff', 'Firestorm', 'Wraithverge Arc', 'Wraithverge Cross', 'Wraithverge Shaft', 'Frost Shards', 'Arc of Death', 'Bloodscourge Skull', 'Bloodscourge Stub', 'Bloodscourge Stick', },
}
