# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from typing import Dict, TypedDict, List, Set 


class LocationDict(TypedDict, total=False): 
    name: str 
    hub: int 
    check_sanity: bool 
    map: int 
    index: int # Thing index as it is stored in the wad file. 
    doom_type: int # In case index end up unreliable, we can use doom type. Maps have often only one of each important things. 
    region: str 


location_table: Dict[int, LocationDict] = {
    391000: {'name': 'Seven Portals - Winnowing Hall - Silver Key',
             'hub': 1,
             'check_sanity': False,
             'map': 1,
             'index': 110,
             'region': 'Seven Portals - Winnowing Hall - Emerald Key'},
    391001: {'name': 'Seven Portals - Winnowing Hall - Emerald Key',
             'hub': 1,
             'check_sanity': False,
             'map': 1,
             'index': 121,
             'region': 'Seven Portals - Winnowing Hall - Main'},
    391002: {'name': 'Seven Portals - Winnowing Hall - Platinum Helm',
             'hub': 1,
             'check_sanity': False,
             'map': 1,
             'index': 219,
             'region': 'Seven Portals - Winnowing Hall - Emerald Key'},
    391003: {'name': 'Seven Portals - Seven Portals - Wraithverge Shaft',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 301,
             'region': 'Seven Portals - Seven Portals - Exit Area'},
    391004: {'name': 'Seven Portals - Seven Portals - Quietus Hilt',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 302,
             'region': 'Seven Portals - Seven Portals - Exit Area'},
    391005: {'name': 'Seven Portals - Seven Portals - Bloodscourge Stick',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 303,
             'region': 'Seven Portals - Seven Portals - Exit Area'},
    391006: {'name': 'Seven Portals - Seven Portals - Dragonskin Bracers',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 304,
             'region': 'Seven Portals - Seven Portals - Ice Stairs'},
    391007: {'name': 'Seven Portals - Seven Portals - Frost Shards',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 644,
             'region': 'Seven Portals - Seven Portals - Main'},
    391008: {'name': 'Seven Portals - Seven Portals - Timon\'s Axe',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 645,
             'region': 'Seven Portals - Seven Portals - Main'},
    391009: {'name': 'Seven Portals - Seven Portals - Serpent Staff',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': 646,
             'region': 'Seven Portals - Seven Portals - Main'},
    391010: {'name': 'Seven Portals - Guardian of Ice - Amulet of Warding',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 52,
             'region': 'Seven Portals - Guardian of Ice - South'},
    391011: {'name': 'Seven Portals - Guardian of Ice - Fire Key',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 156,
             'region': 'Seven Portals - Guardian of Ice - Fire Key Access'},
    391012: {'name': 'Seven Portals - Guardian of Ice - Steel Key',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 157,
             'region': 'Seven Portals - Guardian of Ice - South'},
    391013: {'name': 'Seven Portals - Guardian of Ice - Amulet of Warding 2',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 158,
             'region': 'Seven Portals - Guardian of Ice - Main'},
    391014: {'name': 'Seven Portals - Guardian of Ice - Timon\'s Axe',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 159,
             'region': 'Seven Portals - Guardian of Ice - Main'},
    391015: {'name': 'Seven Portals - Guardian of Ice - Mystic Urn',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 160,
             'region': 'Seven Portals - Guardian of Ice - South'},
    391016: {'name': 'Seven Portals - Guardian of Ice - Torch',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': 303,
             'region': 'Seven Portals - Guardian of Ice - South'},
    391017: {'name': 'Seven Portals - Guardian of Fire - Flame Mask',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': 74,
             'region': 'Seven Portals - Guardian of Fire - Main'},
    391018: {'name': 'Seven Portals - Guardian of Fire - Frost Shards',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': 105,
             'region': 'Seven Portals - Guardian of Fire - Main'},
    391019: {'name': 'Seven Portals - Guardian of Fire - Chaos Device',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': 106,
             'region': 'Seven Portals - Guardian of Fire - Fire Key'},
    391020: {'name': 'Seven Portals - Guardian of Fire - Falcon Shield',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': 107,
             'region': 'Seven Portals - Guardian of Fire - Main'},
    391021: {'name': 'Seven Portals - Guardian of Steel - Serpent Staff',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': 7,
             'region': 'Seven Portals - Guardian of Steel - Main'},
    391022: {'name': 'Seven Portals - Guardian of Steel - Mesh Armor',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': 22,
             'region': 'Seven Portals - Guardian of Steel - Main'},
    391023: {'name': 'Seven Portals - Guardian of Steel - Banishment Device',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': 25,
             'region': 'Seven Portals - Guardian of Steel - Steel Key'},
    391024: {'name': 'Seven Portals - Guardian of Steel - Torch',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': 268,
             'region': 'Seven Portals - Guardian of Steel - Ice Area'},
    391025: {'name': 'Seven Portals - Guardian of Steel - Mystic Urn',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': 396,
             'region': 'Seven Portals - Guardian of Steel - Ice Area'},
    391026: {'name': 'Seven Portals - Bright Crucible - Heart of D\'Sparil',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 19,
             'region': 'Seven Portals - Bright Crucible - Main'},
    391027: {'name': 'Seven Portals - Bright Crucible - Amulet of Warding',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 95,
             'region': 'Seven Portals - Bright Crucible - Main'},
    391028: {'name': 'Seven Portals - Bright Crucible - Mesh Armor',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 96,
             'region': 'Seven Portals - Bright Crucible - Main'},
    391029: {'name': 'Seven Portals - Bright Crucible - Falcon Shield',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 97,
             'region': 'Seven Portals - Bright Crucible - Heart'},
    391030: {'name': 'Seven Portals - Bright Crucible - Platinum Helm',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 98,
             'region': 'Seven Portals - Bright Crucible - Main'},
    391031: {'name': 'Seven Portals - Bright Crucible - Icon of the Defender',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': 193,
             'region': 'Seven Portals - Bright Crucible - Heart'},
    391032: {'name': 'Shadow Wood - Darkmere - Serpent Staff',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 115,
             'region': 'Shadow Wood - Darkmere - Main'},
    391033: {'name': 'Shadow Wood - Darkmere - Swamp Key',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 209,
             'region': 'Shadow Wood - Darkmere - Castle Key'},
    391034: {'name': 'Shadow Wood - Darkmere - Castle Key',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 254,
             'region': 'Shadow Wood - Darkmere - Main'},
    391035: {'name': 'Shadow Wood - Darkmere - Amulet of Warding',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 255,
             'region': 'Shadow Wood - Darkmere - Main'},
# This item is outside the map
#    391036: {'name': 'Shadow Wood - Darkmere - Amulet of Warding 2',
#             'hub': 2,
#             'check_sanity': False,
#             'map': 1,
#             'index': 256,
#             'region': 'Shadow Wood - Darkmere - Main'},
    391037: {'name': 'Shadow Wood - Darkmere - Amulet of Warding 3',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 257,
             'region': 'Shadow Wood - Darkmere - Main'},
    391038: {'name': 'Shadow Wood - Darkmere - Porkalator',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 258,
             'region': 'Shadow Wood - Darkmere - Main'},
    391039: {'name': 'Shadow Wood - Darkmere - Porkalator 2',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 259,
             'region': 'Shadow Wood - Darkmere - Main'},
    391040: {'name': 'Shadow Wood - Darkmere - Porkalator 3',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 260,
             'region': 'Shadow Wood - Darkmere - Castle Key'},
# This item is outside the map
#    391041: {'name': 'Shadow Wood - Darkmere - Icon of the Defender',
#             'hub': 2,
#             'check_sanity': False,
#             'map': 1,
#             'index': 261,
#             'region': 'Shadow Wood - Darkmere - Castle Key'},
    391042: {'name': 'Shadow Wood - Darkmere - Icon of the Defender 2',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 262,
             'region': 'Shadow Wood - Darkmere - Main'},
    391043: {'name': 'Shadow Wood - Darkmere - Icon of the Defender 3',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': 263,
             'region': 'Shadow Wood - Darkmere - Castle Key'},
    391044: {'name': 'Shadow Wood - Caves of Circe - Mesh Armor',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': 115,
             'region': 'Shadow Wood - Caves of Circe - Main'},
    391045: {'name': 'Shadow Wood - Caves of Circe - Chaos Device',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': 116,
             'region': 'Shadow Wood - Caves of Circe - Main'},
    391046: {'name': 'Shadow Wood - Caves of Circe - Frost Shards',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': 131,
             'region': 'Shadow Wood - Caves of Circe - Main'},
    391047: {'name': 'Shadow Wood - Caves of Circe - Cave Key',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': 132,
             'region': 'Shadow Wood - Caves of Circe - Main'},
    391048: {'name': 'Shadow Wood - Caves of Circe - Porkalator',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': 209,
             'region': 'Shadow Wood - Caves of Circe - Main'},
# this item is a trap
#    391049: {'name': 'Shadow Wood - Caves of Circe - Platinum Helm',
#             'hub': 2,
#             'check_sanity': False,
#             'map': 2,
#             'index': 239,
#             'region': 'Shadow Wood - Caves of Circe - Main'},
    391050: {'name': 'Shadow Wood - Wastelands - Krater of Might',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 73,
             'region': 'Shadow Wood - Wastelands - Swamp Key'},
    391051: {'name': 'Shadow Wood - Wastelands - Timon\'s Axe',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 150,
             'region': 'Shadow Wood - Wastelands - Main'},
    391052: {'name': 'Shadow Wood - Wastelands - Boots of Speed',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 151,
             'region': 'Shadow Wood - Wastelands - Main'},
    391053: {'name': 'Shadow Wood - Wastelands - Krater of Might 2',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 152,
             'region': 'Shadow Wood - Wastelands - Main'},
    391054: {'name': 'Shadow Wood - Wastelands - Porkalator',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 153,
             'region': 'Shadow Wood - Wastelands - Main'},
    391055: {'name': 'Shadow Wood - Wastelands - Falcon Shield',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 154,
             'region': 'Shadow Wood - Wastelands - Main'},
    391056: {'name': 'Shadow Wood - Wastelands - Horn Key',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 155,
             'region': 'Shadow Wood - Wastelands - Main'},
    391057: {'name': 'Shadow Wood - Wastelands - Mystic Urn',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': 156,
             'region': 'Shadow Wood - Wastelands - Cave Key'},
    391058: {'name': 'Shadow Wood - Sacred Grove - Mystic Urn',
             'hub': 2,
             'check_sanity': False,
             'map': 4,
             'index': 62,
             'region': 'Shadow Wood - Sacred Grove - Main'},
    391059: {'name': 'Shadow Wood - Sacred Grove - Mystic Urn 2',
             'hub': 2,
             'check_sanity': False,
             'map': 4,
             'index': 63,
             'region': 'Shadow Wood - Sacred Grove - Main'},
    391060: {'name': 'Shadow Wood - Sacred Grove - Mystic Urn 3',
             'hub': 2,
             'check_sanity': False,
             'map': 4,
             'index': 64,
             'region': 'Shadow Wood - Sacred Grove - Main'},
    391061: {'name': 'Shadow Wood - Hypostyle - Mystic Urn',
             'hub': 2,
             'check_sanity': False,
             'map': 5,
             'index': 63,
             'region': 'Shadow Wood - Hypostyle - Main'},
    391062: {'name': 'Shadow Wood - Hypostyle - Wraithverge Cross',
             'hub': 2,
             'check_sanity': False,
             'map': 5,
             'index': 79,
             'region': 'Shadow Wood - Hypostyle - Main'},
    391063: {'name': 'Shadow Wood - Hypostyle - Bloodscourge Stub',
             'hub': 2,
             'check_sanity': False,
             'map': 5,
             'index': 80,
             'region': 'Shadow Wood - Hypostyle - Main'},
    391064: {'name': 'Shadow Wood - Hypostyle - Quietus Cross',
             'hub': 2,
             'check_sanity': False,
             'map': 5,
             'index': 81,
             'region': 'Shadow Wood - Hypostyle - Main'},
    391065: {'name': 'Shadow Wood - Shadow Wood - Platinum Helm',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 209,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391066: {'name': 'Shadow Wood - Shadow Wood - Dark Servant',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 210,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391067: {'name': 'Shadow Wood - Shadow Wood - Chaos Device',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 211,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391068: {'name': 'Shadow Wood - Shadow Wood - Dragonskin Bracers',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 212,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391069: {'name': 'Shadow Wood - Shadow Wood - Firestorm',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 213,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391070: {'name': 'Shadow Wood - Shadow Wood - Hammer of Retribution',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 214,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391071: {'name': 'Shadow Wood - Shadow Wood - Arc of Death',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 215,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391072: {'name': 'Shadow Wood - Shadow Wood - Mystic Urn',
             'hub': 2,
             'check_sanity': False,
             'map': 6,
             'index': 330,
             'region': 'Shadow Wood - Shadow Wood - Main'},
    391073: {'name': 'Castle of Grief - Forsaken Outpost - Rusted Key',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 135,
             'region': 'Castle of Grief - Forsaken Outpost - Main'},
    391074: {'name': 'Castle of Grief - Forsaken Outpost - Timon\'s Axe',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 148,
             'region': 'Castle of Grief - Forsaken Outpost - Rusted Key'},
    391075: {'name': 'Castle of Grief - Forsaken Outpost - Porkalator',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 149,
             'region': 'Castle of Grief - Forsaken Outpost - Main'},
    391076: {'name': 'Castle of Grief - Forsaken Outpost - Boots of Speed',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 150,
             'region': 'Castle of Grief - Forsaken Outpost - From Effluvium'},
    391077: {'name': 'Castle of Grief - Forsaken Outpost - Platinum Helm',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 151,
             'region': 'Castle of Grief - Forsaken Outpost - Main'},
    391078: {'name': 'Castle of Grief - Forsaken Outpost - Daemon Codex',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 152,
             'region': 'Castle of Grief - Forsaken Outpost - Rusted Key'},
    391079: {'name': 'Castle of Grief - Forsaken Outpost - Liber Oscura',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': 153,
             'region': 'Castle of Grief - Forsaken Outpost - Main'},
    391080: {'name': 'Castle of Grief - Castle of Grief - Amulet of Warding',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 153,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391081: {'name': 'Castle of Grief - Castle of Grief - Krater of Might',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 154,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391082: {'name': 'Castle of Grief - Castle of Grief - Dark Servant',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 155,
             'region': 'Castle of Grief - Castle of Grief - Gibbet Access'},
    391083: {'name': 'Castle of Grief - Castle of Grief - Clock Gear 4',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 256,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391084: {'name': 'Castle of Grief - Castle of Grief - Clock Gear 1',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 257,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391085: {'name': 'Castle of Grief - Castle of Grief - Clock Gear 3',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 258,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391086: {'name': 'Castle of Grief - Castle of Grief - Clock Gear 2',
             'hub': 4,
             'check_sanity': False,
             'map': 2,
             'index': 259,
             'region': 'Castle of Grief - Castle of Grief - Main'},
    391087: {'name': 'Castle of Grief - Gibbet - Yorick\'s Skull',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 54,
             'region': 'Castle of Grief - Gibbet - Library'},
    391088: {'name': 'Castle of Grief - Gibbet - Axe Key',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 89,
             'region': 'Castle of Grief - Gibbet - Axe Key Cage'},
    391089: {'name': 'Castle of Grief - Gibbet - Icon of the Defender',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 103,
             'region': 'Castle of Grief - Gibbet - Axe Key'},
    391090: {'name': 'Castle of Grief - Gibbet - Dragonskin Bracers',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 203,
             'region': 'Castle of Grief - Gibbet - Main'},
    391091: {'name': 'Castle of Grief - Gibbet - Firestorm',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 311,
             'region': 'Castle of Grief - Gibbet - Library'},
    391092: {'name': 'Castle of Grief - Gibbet - Hammer of Retribution',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 312,
             'region': 'Castle of Grief - Gibbet - Main'},
    391093: {'name': 'Castle of Grief - Gibbet - Arc of Death',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 313,
             'region': 'Castle of Grief - Gibbet - Main'},
    391094: {'name': 'Castle of Grief - Gibbet - Porkalator',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': 470,
             'region': 'Castle of Grief - Gibbet - Main'},
    391095: {'name': 'Castle of Grief - Effluvium - Falcon Shield',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 104,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391096: {'name': 'Castle of Grief - Effluvium - Mystic Urn',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 105,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391097: {'name': 'Castle of Grief - Effluvium - Porkalator',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 106,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391098: {'name': 'Castle of Grief - Effluvium - Serpent Staff',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 120,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391099: {'name': 'Castle of Grief - Effluvium - Dragonskin Bracers',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 121,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391100: {'name': 'Castle of Grief - Effluvium - Krater of Might',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 183,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391101: {'name': 'Castle of Grief - Effluvium - Dungeon Key',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 233,
             'region': 'Castle of Grief - Effluvium - Main'},
    391102: {'name': 'Castle of Grief - Effluvium - Torch',
             'hub': 4,
             'check_sanity': False,
             'map': 4,
             'index': 268,
             'region': 'Castle of Grief - Effluvium - Dungeons'},
    391103: {'name': 'Castle of Grief - Dungeons - Mesh Armor',
             'hub': 4,
             'check_sanity': False,
             'map': 5,
             'index': 247,
             'region': 'Castle of Grief - Dungeons - Main'},
    391104: {'name': 'Castle of Grief - Dungeons - Porkalator',
             'hub': 4,
             'check_sanity': False,
             'map': 5,
             'index': 248,
             'region': 'Castle of Grief - Dungeons - Main'},
    391105: {'name': 'Castle of Grief - Dungeons - Frost Shards',
             'hub': 4,
             'check_sanity': False,
             'map': 5,
             'index': 265,
             'region': 'Castle of Grief - Dungeons - Main'},
    391106: {'name': 'Castle of Grief - Desolate Garden - Krater of Might',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 65,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391107: {'name': 'Castle of Grief - Desolate Garden - Timon\'s Axe',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 66,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391108: {'name': 'Castle of Grief - Desolate Garden - Serpent Staff',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 67,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391109: {'name': 'Castle of Grief - Desolate Garden - Frost Shards',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 68,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391110: {'name': 'Castle of Grief - Desolate Garden - Arc of Death',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 69,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391111: {'name': 'Castle of Grief - Desolate Garden - Firestorm',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 70,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391112: {'name': 'Castle of Grief - Desolate Garden - Hammer of Retribution',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 71,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391113: {'name': 'Castle of Grief - Desolate Garden - Quietus Hilt',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 72,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391114: {'name': 'Castle of Grief - Desolate Garden - Quietus Cross',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 73,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391115: {'name': 'Castle of Grief - Desolate Garden - Quietus Blade',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 74,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391116: {'name': 'Castle of Grief - Desolate Garden - Wraithverge Shaft',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 75,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391117: {'name': 'Castle of Grief - Desolate Garden - Wraithverge Cross',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 76,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391118: {'name': 'Castle of Grief - Desolate Garden - Wraithverge Arc',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 77,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391119: {'name': 'Castle of Grief - Desolate Garden - Bloodscourge Stick',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 78,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391120: {'name': 'Castle of Grief - Desolate Garden - Bloodscourge Stub',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 79,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391121: {'name': 'Castle of Grief - Desolate Garden - Bloodscourge Skull',
             'hub': 4,
             'check_sanity': False,
             'map': 6,
             'index': 80,
             'region': 'Castle of Grief - Desolate Garden - Main'},
    391122: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Icon of the Defender',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 75,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Main'},
    391123: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Wraithverge Arc',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 108,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Main'},
    391124: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Quietus Blade',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 109,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Main'},
    391125: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Bloodscourge Skull',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 110,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Main'},
    391126: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Falcon Shield',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 344,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Main'},
    391127: {'name': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Boots of Speed',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': 345,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Chapel Access'},
    391128: {'name': 'Heresiarch\'s Seminary - Dragon Chapel - Mystic Urn',
             'hub': 3,
             'check_sanity': False,
             'map': 2,
             'index': 104,
             'region': 'Heresiarch\'s Seminary - Dragon Chapel - Main'},
    391129: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Falcon Shield',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': 60,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Wolf'},
    391130: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Chaos Device',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': 119,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Main'},
    391131: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Torch',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': 193,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Main'},
    391132: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Bloodscourge Skull',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': 195,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Wolf'},
    391133: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Porkalator',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': 217,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Wolf'},
    391134: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Krater of Might',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 73,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391135: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Platinum Helm',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 74,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391136: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Serpent Staff',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 83,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391137: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Firestorm',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 84,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391138: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Timon\'s Axe',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 85,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391139: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Hammer of Retribution',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 86,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391140: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Frost Shards',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 87,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391141: {'name': 'Heresiarch\'s Seminary - Deathwind Chapel - Arc of Death',
             'hub': 3,
             'check_sanity': False,
             'map': 4,
             'index': 88,
             'region': 'Heresiarch\'s Seminary - Deathwind Chapel - Main'},
    391142: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Sapphire Planet',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 5,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391143: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Emerald Planet',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 6,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391144: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Amulet of Warding',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 62,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391145: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Porkalator',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 63,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391146: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Timon\'s Axe',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 134,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391147: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Serpent Staff',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 135,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391148: {'name': 'Heresiarch\'s Seminary - Orchard of Lamentations - Frost Shards',
             'hub': 3,
             'check_sanity': False,
             'map': 5,
             'index': 136,
             'region': 'Heresiarch\'s Seminary - Orchard of Lamentations - Main'},
    391149: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Sapphire Planet',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 19,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391150: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Emerald Planet',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 20,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391151: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Ruby Planet',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 21,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391152: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Porkalator',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 70,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391153: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Mesh Armor',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 71,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391154: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Hammer of Retribution',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 72,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391155: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Firestorm',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 73,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391156: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Arc of Death',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 74,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391157: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Torch',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 131,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391158: {'name': 'Heresiarch\'s Seminary - Silent Refectory - Banishment Device',
             'hub': 3,
             'check_sanity': False,
             'map': 6,
             'index': 156,
             'region': 'Heresiarch\'s Seminary - Silent Refectory - Main'},
    391159: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Wraithverge Arc',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': 42,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin'},
    391160: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Banishment Device',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': 43,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin'},
    391161: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Dragonskin Bracers',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': 44,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin'},
    391162: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Icon of the Defender',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': 174,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Dragon'},
    391163: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Krater of Might',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': 276,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin'},
    391164: {'name': 'Necropolis - Necropolis - Krater of Might',
             'hub': 5,
             'check_sanity': False,
             'map': 1,
             'index': 76,
             'region': 'Necropolis - Necropolis - Main'},
    391165: {'name': 'Necropolis - Necropolis - Boots of Speed',
             'hub': 5,
             'check_sanity': False,
             'map': 1,
             'index': 77,
             'region': 'Necropolis - Necropolis - Main'},
    391166: {'name': 'Necropolis - Necropolis - Platinum Helm',
             'hub': 5,
             'check_sanity': False,
             'map': 1,
             'index': 78,
             'region': 'Necropolis - Necropolis - Main'},
    391167: {'name': 'Necropolis - Zedek\'s Tomb - Mesh Armor',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 87,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391168: {'name': 'Necropolis - Zedek\'s Tomb - Porkalator',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 88,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391169: {'name': 'Necropolis - Zedek\'s Tomb - Banishment Device',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 89,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391170: {'name': 'Necropolis - Zedek\'s Tomb - Quietus Hilt',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 90,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391171: {'name': 'Necropolis - Zedek\'s Tomb - Quietus Cross',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 91,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391172: {'name': 'Necropolis - Zedek\'s Tomb - Quietus Blade',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 92,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391173: {'name': 'Necropolis - Zedek\'s Tomb - Glaive Seal',
             'hub': 5,
             'check_sanity': False,
             'map': 2,
             'index': 242,
             'region': 'Necropolis - Zedek\'s Tomb - Main'},
    391174: {'name': 'Necropolis - Menelkir\'s Tomb - Bloodscourge Stick',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 58,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391175: {'name': 'Necropolis - Menelkir\'s Tomb - Bloodscourge Stub',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 59,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391176: {'name': 'Necropolis - Menelkir\'s Tomb - Bloodscourge Skull',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 60,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391177: {'name': 'Necropolis - Menelkir\'s Tomb - Mystic Urn',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 61,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391178: {'name': 'Necropolis - Menelkir\'s Tomb - Dragonskin Bracers',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 62,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391179: {'name': 'Necropolis - Menelkir\'s Tomb - Sigil of the Magus',
             'hub': 5,
             'check_sanity': False,
             'map': 3,
             'index': 203,
             'region': 'Necropolis - Menelkir\'s Tomb - Main'},
    391180: {'name': 'Necropolis - Traductus\' Tomb - Falcon Shield',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 6,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391181: {'name': 'Necropolis - Traductus\' Tomb - Icon of the Defender',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 7,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391182: {'name': 'Necropolis - Traductus\' Tomb - Wraithverge Shaft',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 8,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391183: {'name': 'Necropolis - Traductus\' Tomb - Wraithverge Cross',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 9,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391184: {'name': 'Necropolis - Traductus\' Tomb - Wraithverge Arc',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 10,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391185: {'name': 'Necropolis - Traductus\' Tomb - Holy Relic',
             'hub': 5,
             'check_sanity': False,
             'map': 4,
             'index': 134,
             'region': 'Necropolis - Traductus\' Tomb - Main'},
    391186: {'name': 'Necropolis - Vivarium - Dragonskin Bracers',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 103,
             'region': 'Necropolis - Vivarium - Main'},
    391187: {'name': 'Necropolis - Vivarium - Mystic Urn',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 104,
             'region': 'Necropolis - Vivarium - Main'},
    391188: {'name': 'Necropolis - Vivarium - Amulet of Warding',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 109,
             'region': 'Necropolis - Vivarium - Main'},
    391189: {'name': 'Necropolis - Vivarium - Mesh Armor',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 110,
             'region': 'Necropolis - Vivarium - Main'},
    391190: {'name': 'Necropolis - Vivarium - Platinum Helm',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 111,
             'region': 'Necropolis - Vivarium - Main'},
    391191: {'name': 'Necropolis - Vivarium - Falcon Shield',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 112,
             'region': 'Necropolis - Vivarium - Main'},
    391192: {'name': 'Necropolis - Vivarium - Banishment Device',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 113,
             'region': 'Necropolis - Vivarium - Main'},
    391193: {'name': 'Necropolis - Vivarium - Serpent Staff',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 163,
             'region': 'Necropolis - Vivarium - Main'},
    391194: {'name': 'Necropolis - Vivarium - Timon\'s Axe',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 164,
             'region': 'Necropolis - Vivarium - Main'},
    391195: {'name': 'Necropolis - Vivarium - Frost Shards',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 165,
             'region': 'Necropolis - Vivarium - Main'},
    391196: {'name': 'Necropolis - Vivarium - Porkalator',
             'hub': 5,
             'check_sanity': False,
             'map': 5,
             'index': 179,
             'region': 'Necropolis - Vivarium - Main'},
    391197: {'name': 'Necropolis - Dark Crucible - Mystic Urn',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 472,
             'region': 'Necropolis - Dark Crucible - Main'},
    391198: {'name': 'Necropolis - Dark Crucible - Mystic Urn 2',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 473,
             'region': 'Necropolis - Dark Crucible - Main'},
    391199: {'name': 'Necropolis - Dark Crucible - Krater of Might',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 474,
             'region': 'Necropolis - Dark Crucible - Main'},
    391200: {'name': 'Necropolis - Dark Crucible - Krater of Might 2',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 475,
             'region': 'Necropolis - Dark Crucible - Main'},
    391201: {'name': 'Necropolis - Dark Crucible - Krater of Might 3',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 476,
             'region': 'Necropolis - Dark Crucible - Main'},
    391202: {'name': 'Necropolis - Dark Crucible - Krater of Might 4',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 477,
             'region': 'Necropolis - Dark Crucible - Main'},
    391203: {'name': 'Necropolis - Dark Crucible - Krater of Might 5',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 478,
             'region': 'Necropolis - Dark Crucible - Main'},
    391204: {'name': 'Necropolis - Dark Crucible - Krater of Might 6',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': 479,
             'region': 'Necropolis - Dark Crucible - Main'},
    391205: {'name': 'Seven Portals - Guardian of Fire - West Door Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': -3,
             'region': 'Seven Portals - Guardian of Fire - Main'},
    391206: {'name': 'Seven Portals - Guardian of Steel - West Door Switch North',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': -3,
             'region': 'Seven Portals - Guardian of Steel - Main'},
    391207: {'name': 'Seven Portals - Guardian of Steel - West Door Switch South',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': -4,
             'region': 'Seven Portals - Guardian of Steel - Main'},
    391208: {'name': 'Seven Portals - Seven Portals - Ice Stairs Exit Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -3,
             'region': 'Seven Portals - Seven Portals - Ice Stairs'},
    391209: {'name': 'Seven Portals - Seven Portals - Steel Stairs Exit Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -4,
             'region': 'Seven Portals - Seven Portals - Steel Stairs'},
    391210: {'name': 'Seven Portals - Seven Portals - Steel Stairs Puzzle Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -5,
             'region': 'Seven Portals - Seven Portals - Steel Stairs'},
    391211: {'name': 'Seven Portals - Seven Portals - Fire Stairs Exit Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -6,
             'region': 'Seven Portals - Seven Portals - Fire Stairs'},
    391212: {'name': 'Seven Portals - Seven Portals - Fire Stairs Puzzle Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -7,
             'region': 'Seven Portals - Seven Portals - Fire Stairs'},
    391213: {'name': 'Seven Portals - Guardian of Ice - Ice Stairs Trigger',
             'hub': 1,
             'check_sanity': False,
             'map': 3,
             'index': -3,
             'region': 'Seven Portals - Guardian of Ice - South'},
    391214: {'name': 'Seven Portals - Guardian of Fire - Fire Stairs Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': -4,
             'region': 'Seven Portals - Guardian of Fire - Fire Key'},
    391215: {'name': 'Seven Portals - Guardian of Steel - Steel Stairs Switches',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': -5,
             'region': 'Seven Portals - Guardian of Steel - Steel Key'},
    391216: {'name': 'Seven Portals - Guardian of Fire - Bright Crucible Switch',
             'hub': 1,
             'check_sanity': False,
             'map': 4,
             'index': -5,
             'region': 'Seven Portals - Guardian of Fire - Ice Area'},
    391217: {'name': 'Seven Portals - Guardian of Steel - Bright Crucible Trigger',
             'hub': 1,
             'check_sanity': False,
             'map': 5,
             'index': -6,
             'region': 'Seven Portals - Guardian of Steel - Ice Area'},
    391218: {'name': 'Seven Portals - Bright Crucible - Exit Trigger',
             'hub': 1,
             'check_sanity': False,
             'map': 6,
             'index': -3,
             'region': 'Seven Portals - Bright Crucible - Heart'},
    391219: {'name': 'Shadow Wood - Darkmere - Horn Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': -3,
             'region': 'Shadow Wood - Darkmere - Horn Key'},
    391220: {'name': 'Shadow Wood - Darkmere - Cave Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 1,
             'index': -4,
             'region': 'Shadow Wood - Darkmere - Cave Key'},
    391221: {'name': 'Shadow Wood - Caves of Circe - Horn Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': -3,
             'region': 'Shadow Wood - Caves of Circe - Horn Key'},
    391222: {'name': 'Shadow Wood - Caves of Circe - Swamp Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 2,
             'index': -4,
             'region': 'Shadow Wood - Caves of Circe - Swamp Key'},
    391223: {'name': 'Shadow Wood - Wastelands - Cave Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': -3,
             'region': 'Shadow Wood - Wastelands - Cave Key'},
    391224: {'name': 'Shadow Wood - Wastelands - Swamp Key Puzzle Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 3,
             'index': -4,
             'region': 'Shadow Wood - Wastelands - Swamp Key'},
    391225: {'name': 'Shadow Wood - Sacred Grove - Desolate Garden Switch',
             'hub': 2,
             'check_sanity': False,
             'map': 4,
             'index': -3,
             'region': 'Shadow Wood - Sacred Grove - Main'},
    391226: {'name': 'Heresiarch\'s Seminary - Dragon Chapel - Dragon Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 2,
             'index': -3,
             'region': 'Heresiarch\'s Seminary - Dragon Chapel - Main'},
    391227: {'name': 'Heresiarch\'s Seminary - Dragon Chapel - Wolf Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 2,
             'index': -4,
             'region': 'Heresiarch\'s Seminary - Dragon Chapel - Wolf'},
    391228: {'name': 'Heresiarch\'s Seminary - Dragon Chapel - Griffin Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 2,
             'index': -5,
             'region': 'Heresiarch\'s Seminary - Dragon Chapel - Griffin'},
    391229: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Wolf Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': -3,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Main'},
    391230: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Dragon Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': -4,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Dragon'},
    391231: {'name': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin Puzzle Trigger',
             'hub': 3,
             'check_sanity': False,
             'map': 7,
             'index': -5,
             'region': 'Heresiarch\'s Seminary - Wolf Chapel - Griffin'},
    391232: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Griffin Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': -3,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Main'},
    391233: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Dragon Puzzle Switch',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': -4,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Dragon'},
    391234: {'name': 'Heresiarch\'s Seminary - Griffin Chapel - Wolf Puzzle Trigger',
             'hub': 3,
             'check_sanity': False,
             'map': 3,
             'index': -5,
             'region': 'Heresiarch\'s Seminary - Griffin Chapel - Wolf'},
    391235: {'name': 'Castle of Grief - Forsaken Outpost - From Effluvium Trigger',
             'hub': 4,
             'check_sanity': False,
             'map': 1,
             'index': -3,
             'region': 'Castle of Grief - Forsaken Outpost - From Effluvium'},
    391236: {'name': 'Seven Portals - Exit',
             'hub': 1,
             'check_sanity': False,
             'map': 2,
             'index': -1,
             'region': 'Seven Portals - Seven Portals - Exit Area'},
    391237: {'name': 'Shadow Wood - Exit',
             'hub': 2,
             'check_sanity': False,
             'map': 5,
             'index': -1,
             'region': 'Shadow Wood - Hypostyle - Main'},
    391238: {'name': 'Heresiarch\'s Seminary - Exit',
             'hub': 3,
             'check_sanity': False,
             'map': 1,
             'index': -1,
             'region': 'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Exit Area'},
    391239: {'name': 'Castle of Grief - Exit',
             'hub': 4,
             'check_sanity': False,
             'map': 3,
             'index': -1,
             'region': 'Castle of Grief - Gibbet - Axe Key'},
    391240: {'name': 'Necropolis - Exit',
             'hub': 5,
             'check_sanity': False,
             'map': 6,
             'index': -1,
             'region': 'Necropolis - Dark Crucible - Main'},
}


location_name_groups: Dict[str, Set[str]] = {
    'Seven Portals': {
        'Seven Portals - Winnowing Hall - Silver Key',
        'Seven Portals - Winnowing Hall - Emerald Key',
        'Seven Portals - Winnowing Hall - Platinum Helm',
        'Seven Portals - Seven Portals - Wraithverge Shaft',
        'Seven Portals - Seven Portals - Quietus Hilt',
        'Seven Portals - Seven Portals - Bloodscourge Stick',
        'Seven Portals - Seven Portals - Dragonskin Bracers',
        'Seven Portals - Seven Portals - Frost Shards',
        'Seven Portals - Seven Portals - Timon\'s Axe',
        'Seven Portals - Seven Portals - Serpent Staff',
        'Seven Portals - Guardian of Ice - Amulet of Warding',
        'Seven Portals - Guardian of Ice - Fire Key',
        'Seven Portals - Guardian of Ice - Steel Key',
        'Seven Portals - Guardian of Ice - Amulet of Warding 2',
        'Seven Portals - Guardian of Ice - Timon\'s Axe',
        'Seven Portals - Guardian of Ice - Mystic Urn',
        'Seven Portals - Guardian of Ice - Torch',
        'Seven Portals - Guardian of Fire - Flame Mask',
        'Seven Portals - Guardian of Fire - Frost Shards',
        'Seven Portals - Guardian of Fire - Chaos Device',
        'Seven Portals - Guardian of Fire - Falcon Shield',
        'Seven Portals - Guardian of Steel - Serpent Staff',
        'Seven Portals - Guardian of Steel - Mesh Armor',
        'Seven Portals - Guardian of Steel - Banishment Device',
        'Seven Portals - Guardian of Steel - Torch',
        'Seven Portals - Guardian of Steel - Mystic Urn',
        'Seven Portals - Bright Crucible - Heart of D\'Sparil',
        'Seven Portals - Bright Crucible - Amulet of Warding',
        'Seven Portals - Bright Crucible - Mesh Armor',
        'Seven Portals - Bright Crucible - Falcon Shield',
        'Seven Portals - Bright Crucible - Platinum Helm',
        'Seven Portals - Bright Crucible - Icon of the Defender',
        'Seven Portals - Guardian of Fire - West Door Switch',
        'Seven Portals - Guardian of Steel - West Door Switch North',
        'Seven Portals - Guardian of Steel - West Door Switch South',
        'Seven Portals - Seven Portals - Ice Stairs Exit Switch',
        'Seven Portals - Seven Portals - Steel Stairs Exit Switch',
        'Seven Portals - Seven Portals - Steel Stairs Puzzle Switch',
        'Seven Portals - Seven Portals - Fire Stairs Exit Switch',
        'Seven Portals - Seven Portals - Fire Stairs Puzzle Switch',
        'Seven Portals - Guardian of Ice - Ice Stairs Trigger',
        'Seven Portals - Guardian of Fire - Fire Stairs Switch',
        'Seven Portals - Guardian of Steel - Steel Stairs Switches',
        'Seven Portals - Guardian of Fire - Bright Crucible Switch',
        'Seven Portals - Guardian of Steel - Bright Crucible Trigger',
        'Seven Portals - Bright Crucible - Exit Trigger',
        'Seven Portals - Exit',
    },
    'Shadow Wood': {
        'Shadow Wood - Darkmere - Serpent Staff',
        'Shadow Wood - Darkmere - Swamp Key',
        'Shadow Wood - Darkmere - Castle Key',
        'Shadow Wood - Darkmere - Amulet of Warding',
        'Shadow Wood - Darkmere - Amulet of Warding 2',
        'Shadow Wood - Darkmere - Amulet of Warding 3',
        'Shadow Wood - Darkmere - Porkalator',
        'Shadow Wood - Darkmere - Porkalator 2',
        'Shadow Wood - Darkmere - Porkalator 3',
        'Shadow Wood - Darkmere - Icon of the Defender',
        'Shadow Wood - Darkmere - Icon of the Defender 2',
        'Shadow Wood - Darkmere - Icon of the Defender 3',
        'Shadow Wood - Caves of Circe - Mesh Armor',
        'Shadow Wood - Caves of Circe - Chaos Device',
        'Shadow Wood - Caves of Circe - Frost Shards',
        'Shadow Wood - Caves of Circe - Cave Key',
        'Shadow Wood - Caves of Circe - Porkalator',
        'Shadow Wood - Caves of Circe - Platinum Helm',
        'Shadow Wood - Wastelands - Krater of Might',
        'Shadow Wood - Wastelands - Timon\'s Axe',
        'Shadow Wood - Wastelands - Boots of Speed',
        'Shadow Wood - Wastelands - Krater of Might 2',
        'Shadow Wood - Wastelands - Porkalator',
        'Shadow Wood - Wastelands - Falcon Shield',
        'Shadow Wood - Wastelands - Horn Key',
        'Shadow Wood - Wastelands - Mystic Urn',
        'Shadow Wood - Sacred Grove - Mystic Urn',
        'Shadow Wood - Sacred Grove - Mystic Urn 2',
        'Shadow Wood - Sacred Grove - Mystic Urn 3',
        'Shadow Wood - Hypostyle - Mystic Urn',
        'Shadow Wood - Hypostyle - Wraithverge Cross',
        'Shadow Wood - Hypostyle - Bloodscourge Stub',
        'Shadow Wood - Hypostyle - Quietus Cross',
        'Shadow Wood - Shadow Wood - Platinum Helm',
        'Shadow Wood - Shadow Wood - Dark Servant',
        'Shadow Wood - Shadow Wood - Chaos Device',
        'Shadow Wood - Shadow Wood - Dragonskin Bracers',
        'Shadow Wood - Shadow Wood - Firestorm',
        'Shadow Wood - Shadow Wood - Hammer of Retribution',
        'Shadow Wood - Shadow Wood - Arc of Death',
        'Shadow Wood - Shadow Wood - Mystic Urn',
        'Shadow Wood - Darkmere - Horn Key Puzzle Switch',
        'Shadow Wood - Darkmere - Cave Key Puzzle Switch',
        'Shadow Wood - Caves of Circe - Horn Key Puzzle Switch',
        'Shadow Wood - Caves of Circe - Swamp Key Puzzle Switch',
        'Shadow Wood - Wastelands - Cave Key Puzzle Switch',
        'Shadow Wood - Wastelands - Swamp Key Puzzle Switch',
        'Shadow Wood - Sacred Grove - Desolate Garden Switch',
        'Shadow Wood - Exit',
    },
    'Heresiarch\'s Seminary': {
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Icon of the Defender',
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Wraithverge Arc',
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Quietus Blade',
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Bloodscourge Skull',
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Falcon Shield',
        'Heresiarch\'s Seminary - Heresiarch\'s Seminary - Boots of Speed',
        'Heresiarch\'s Seminary - Dragon Chapel - Mystic Urn',
        'Heresiarch\'s Seminary - Griffin Chapel - Falcon Shield',
        'Heresiarch\'s Seminary - Griffin Chapel - Chaos Device',
        'Heresiarch\'s Seminary - Griffin Chapel - Torch',
        'Heresiarch\'s Seminary - Griffin Chapel - Bloodscourge Skull',
        'Heresiarch\'s Seminary - Griffin Chapel - Porkalator',
        'Heresiarch\'s Seminary - Deathwind Chapel - Krater of Might',
        'Heresiarch\'s Seminary - Deathwind Chapel - Platinum Helm',
        'Heresiarch\'s Seminary - Deathwind Chapel - Serpent Staff',
        'Heresiarch\'s Seminary - Deathwind Chapel - Firestorm',
        'Heresiarch\'s Seminary - Deathwind Chapel - Timon\'s Axe',
        'Heresiarch\'s Seminary - Deathwind Chapel - Hammer of Retribution',
        'Heresiarch\'s Seminary - Deathwind Chapel - Frost Shards',
        'Heresiarch\'s Seminary - Deathwind Chapel - Arc of Death',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Sapphire Planet',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Emerald Planet',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Amulet of Warding',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Porkalator',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Timon\'s Axe',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Serpent Staff',
        'Heresiarch\'s Seminary - Orchard of Lamentations - Frost Shards',
        'Heresiarch\'s Seminary - Silent Refectory - Sapphire Planet',
        'Heresiarch\'s Seminary - Silent Refectory - Emerald Planet',
        'Heresiarch\'s Seminary - Silent Refectory - Ruby Planet',
        'Heresiarch\'s Seminary - Silent Refectory - Porkalator',
        'Heresiarch\'s Seminary - Silent Refectory - Mesh Armor',
        'Heresiarch\'s Seminary - Silent Refectory - Hammer of Retribution',
        'Heresiarch\'s Seminary - Silent Refectory - Firestorm',
        'Heresiarch\'s Seminary - Silent Refectory - Arc of Death',
        'Heresiarch\'s Seminary - Silent Refectory - Torch',
        'Heresiarch\'s Seminary - Silent Refectory - Banishment Device',
        'Heresiarch\'s Seminary - Wolf Chapel - Wraithverge Arc',
        'Heresiarch\'s Seminary - Wolf Chapel - Banishment Device',
        'Heresiarch\'s Seminary - Wolf Chapel - Dragonskin Bracers',
        'Heresiarch\'s Seminary - Wolf Chapel - Icon of the Defender',
        'Heresiarch\'s Seminary - Wolf Chapel - Krater of Might',
        'Heresiarch\'s Seminary - Dragon Chapel - Dragon Puzzle Switch',
        'Heresiarch\'s Seminary - Dragon Chapel - Wolf Puzzle Switch',
        'Heresiarch\'s Seminary - Dragon Chapel - Griffin Puzzle Switch',
        'Heresiarch\'s Seminary - Wolf Chapel - Wolf Puzzle Switch',
        'Heresiarch\'s Seminary - Wolf Chapel - Dragon Puzzle Switch',
        'Heresiarch\'s Seminary - Wolf Chapel - Griffin Puzzle Trigger',
        'Heresiarch\'s Seminary - Griffin Chapel - Griffin Puzzle Switch',
        'Heresiarch\'s Seminary - Griffin Chapel - Dragon Puzzle Switch',
        'Heresiarch\'s Seminary - Griffin Chapel - Wolf Puzzle Trigger',
        'Heresiarch\'s Seminary - Exit',
    },
    'Castle of Grief': {
        'Castle of Grief - Forsaken Outpost - Rusted Key',
        'Castle of Grief - Forsaken Outpost - Timon\'s Axe',
        'Castle of Grief - Forsaken Outpost - Porkalator',
        'Castle of Grief - Forsaken Outpost - Boots of Speed',
        'Castle of Grief - Forsaken Outpost - Platinum Helm',
        'Castle of Grief - Forsaken Outpost - Daemon Codex',
        'Castle of Grief - Forsaken Outpost - Liber Oscura',
        'Castle of Grief - Castle of Grief - Amulet of Warding',
        'Castle of Grief - Castle of Grief - Krater of Might',
        'Castle of Grief - Castle of Grief - Dark Servant',
        'Castle of Grief - Castle of Grief - Clock Gear 4',
        'Castle of Grief - Castle of Grief - Clock Gear 1',
        'Castle of Grief - Castle of Grief - Clock Gear 3',
        'Castle of Grief - Castle of Grief - Clock Gear 2',
        'Castle of Grief - Gibbet - Yorick\'s Skull',
        'Castle of Grief - Gibbet - Axe Key',
        'Castle of Grief - Gibbet - Icon of the Defender',
        'Castle of Grief - Gibbet - Dragonskin Bracers',
        'Castle of Grief - Gibbet - Firestorm',
        'Castle of Grief - Gibbet - Hammer of Retribution',
        'Castle of Grief - Gibbet - Arc of Death',
        'Castle of Grief - Gibbet - Porkalator',
        'Castle of Grief - Effluvium - Falcon Shield',
        'Castle of Grief - Effluvium - Mystic Urn',
        'Castle of Grief - Effluvium - Porkalator',
        'Castle of Grief - Effluvium - Serpent Staff',
        'Castle of Grief - Effluvium - Dragonskin Bracers',
        'Castle of Grief - Effluvium - Krater of Might',
        'Castle of Grief - Effluvium - Dungeon Key',
        'Castle of Grief - Effluvium - Torch',
        'Castle of Grief - Dungeons - Mesh Armor',
        'Castle of Grief - Dungeons - Porkalator',
        'Castle of Grief - Dungeons - Frost Shards',
        'Castle of Grief - Desolate Garden - Krater of Might',
        'Castle of Grief - Desolate Garden - Timon\'s Axe',
        'Castle of Grief - Desolate Garden - Serpent Staff',
        'Castle of Grief - Desolate Garden - Frost Shards',
        'Castle of Grief - Desolate Garden - Arc of Death',
        'Castle of Grief - Desolate Garden - Firestorm',
        'Castle of Grief - Desolate Garden - Hammer of Retribution',
        'Castle of Grief - Desolate Garden - Quietus Hilt',
        'Castle of Grief - Desolate Garden - Quietus Cross',
        'Castle of Grief - Desolate Garden - Quietus Blade',
        'Castle of Grief - Desolate Garden - Wraithverge Shaft',
        'Castle of Grief - Desolate Garden - Wraithverge Cross',
        'Castle of Grief - Desolate Garden - Wraithverge Arc',
        'Castle of Grief - Desolate Garden - Bloodscourge Stick',
        'Castle of Grief - Desolate Garden - Bloodscourge Stub',
        'Castle of Grief - Desolate Garden - Bloodscourge Skull',
        'Castle of Grief - Forsaken Outpost - From Effluvium Trigger',
        'Castle of Grief - Exit',
    },
    'Necropolis': {
        'Necropolis - Necropolis - Krater of Might',
        'Necropolis - Necropolis - Boots of Speed',
        'Necropolis - Necropolis - Platinum Helm',
        'Necropolis - Zedek\'s Tomb - Mesh Armor',
        'Necropolis - Zedek\'s Tomb - Porkalator',
        'Necropolis - Zedek\'s Tomb - Banishment Device',
        'Necropolis - Zedek\'s Tomb - Quietus Hilt',
        'Necropolis - Zedek\'s Tomb - Quietus Cross',
        'Necropolis - Zedek\'s Tomb - Quietus Blade',
        'Necropolis - Zedek\'s Tomb - Glaive Seal',
        'Necropolis - Menelkir\'s Tomb - Bloodscourge Stick',
        'Necropolis - Menelkir\'s Tomb - Bloodscourge Stub',
        'Necropolis - Menelkir\'s Tomb - Bloodscourge Skull',
        'Necropolis - Menelkir\'s Tomb - Mystic Urn',
        'Necropolis - Menelkir\'s Tomb - Dragonskin Bracers',
        'Necropolis - Menelkir\'s Tomb - Sigil of the Magus',
        'Necropolis - Traductus\' Tomb - Falcon Shield',
        'Necropolis - Traductus\' Tomb - Icon of the Defender',
        'Necropolis - Traductus\' Tomb - Wraithverge Shaft',
        'Necropolis - Traductus\' Tomb - Wraithverge Cross',
        'Necropolis - Traductus\' Tomb - Wraithverge Arc',
        'Necropolis - Traductus\' Tomb - Holy Relic',
        'Necropolis - Vivarium - Dragonskin Bracers',
        'Necropolis - Vivarium - Mystic Urn',
        'Necropolis - Vivarium - Amulet of Warding',
        'Necropolis - Vivarium - Mesh Armor',
        'Necropolis - Vivarium - Platinum Helm',
        'Necropolis - Vivarium - Falcon Shield',
        'Necropolis - Vivarium - Banishment Device',
        'Necropolis - Vivarium - Serpent Staff',
        'Necropolis - Vivarium - Timon\'s Axe',
        'Necropolis - Vivarium - Frost Shards',
        'Necropolis - Vivarium - Porkalator',
        'Necropolis - Dark Crucible - Mystic Urn',
        'Necropolis - Dark Crucible - Mystic Urn 2',
        'Necropolis - Dark Crucible - Krater of Might',
        'Necropolis - Dark Crucible - Krater of Might 2',
        'Necropolis - Dark Crucible - Krater of Might 3',
        'Necropolis - Dark Crucible - Krater of Might 4',
        'Necropolis - Dark Crucible - Krater of Might 5',
        'Necropolis - Dark Crucible - Krater of Might 6',
        'Necropolis - Exit',
    },
}


death_logic_locations = [
#    'Shadow Wood - Caves of Circe - Platinum Helm'
]
